Content:
    - framework/doc/content
    - modules/ray_tracing/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE Ray Tracing Module
        repo: https://github.com/idaholab/moose
        home: /modules/ray_tracing
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/ray_tracing
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/ray_tracing/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.sqa: disable
