Content:
    - framework/doc/content
    - modules/fluid_structure_interaction/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: fluid_structure_interaction
        repo: https://github.com/idaholab/moose
        home: /modules/fluid_structure_interaction
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/fluid_structure_interaction
        hide:
            framework: !include framework/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/fluid_structure_interaction/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.sqa: disable
